# Generated by Django 2.0.6 on 2018-06-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=3)),
                ('country_flag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_order', models.IntegerField()),
                ('team_one_goal', models.IntegerField()),
                ('team_one_concede', models.IntegerField()),
                ('team_one_gd', models.IntegerField()),
                ('team_one_point', models.IntegerField()),
                ('team_two_goal', models.IntegerField()),
                ('team_two_concede', models.IntegerField()),
                ('team_two_gd', models.IntegerField()),
                ('team_two_point', models.IntegerField()),
                ('date', models.DateField()),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='wc.Country')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='wc.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('team_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_four', to='wc.Country')),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_one', to='wc.Country')),
                ('team_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_three', to='wc.Country')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_two', to='wc.Country')),
            ],
        ),
    ]
