# Generated by Django 2.0.6 on 2018-06-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0002_remove_country_country_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField()),
                ('concede', models.IntegerField()),
                ('gd', models.IntegerField()),
                ('point', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='wc.Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_one_concede',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_one_gd',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_one_goal',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_one_point',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_two_concede',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_two_gd',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_two_goal',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_two_point',
        ),
        migrations.AlterField(
            model_name='match',
            name='team_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='wc.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='wc.Team'),
        ),
    ]
