# Generated by Django 2.0.6 on 2018-06-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0004_auto_20180607_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='match_order',
            field=models.TextField(blank=True, max_length=6, null=True),
        ),
    ]
