# Generated by Django 2.0.6 on 2018-06-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0006_auto_20180607_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='concede',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='gd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
