# Generated by Django 2.0.6 on 2018-06-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0007_auto_20180608_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pen_agn',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='pen_for',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
